### PR TITLE
fix: Dokan dashboard buttons color synchronization issue with dokan color customizer module.

### PR DESCRIPTION
**Pull request by MdAsifHossainNadim**
### Sync Dashboard Buttons with Dokan Color Customizer module.

Before this enhancement, we had issues with dashboard buttons not syncing with the Dokan Color Customizer module. Now, it is working fine.

**Note:  Version bump is required to update/fix this issue**

Issue Link: #55 

**Previous this Fix :**
color-issue-first

**After this Fix :**
Screenshot 2024-03-15 at 11 08 56 AM

### CODE REVIEW

**Comment by shohag121** [comment]
> Note: Version bump is required to update/fix this issue

@MdAsifHossainNadim Bhai, Would you please explain a little?

**Comment by devianadim** [comment]
@shohag121 Vhaiya, When we use the color palette's preset from ```dokan color customizer``` modules, the preset's color combination works fine on vendor dashboard navigation & others. But some places like vendor product page button not reflected perfectly when ```dokani``` theme activated. Because, we are using important clause with our styles from theme end.

**Comment by MdAsifHossainNadim** [comment]
@shohag121 Vhaiya, When we used the color palette's preset from ```dokan color customizer``` modules, the preset's color combination works fine on vendor dashboard navigation & others. But some places like vendor product page button not reflected perfectly when ```dokani``` theme activated. Because, we are using important clause with our styles from theme end.

**Review by shohag121 — APPROVED** [review]

**Comment by MdAsifHossainNadim** [comment]
@shashwatahalder01 Vhai, kindly check this pr at your convenience.
**NB:- We need to remove ```dokani_dynamic_css_output``` key (for bast caching or regenerate style first) from options table before starting this testing.**

**Pull request merged**
